version: "3"
services:
  cassandra:
    container_name: tododb
    image: mysql:5.7.29
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - PGDATA=/data
    volumes:
      - ./workdir/data:/var/lib/mysql
    networks:
      - todoapp-net
networks:
  todoapp-net:
